### ISSUE TITLE
Check box Accesibilidad física

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#1]
el check box de accesibilidad fisica no me convence. Les pido por favor dejar solo estas opciones:
 sanitario adaptado
 elevador
 elevador adaptado
 bebedero adaptado
 estacionamiento exclusivo
 rampa de acceso
 barandilla en escaleras y rampa

**Comment by leogermani** [comment]
Listo,

(no estoy totalmente de acuerdo pero...)
