### ISSUE TITLE
Al agregar imagen en Galeria, eliminar "ou" y sacar soportado.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#10]

**Comment by kterva** [comment]
se cambió en la línea 864 del archivo /mapasculturais/src/protected/application/themes/BaseV1/Theme.php

**Comment by kterva** [comment]
no se sacó "soportado" porque sino no se aclara qué tipos de archivos son soportados para subir a la galería

**Comment by donsalvatore** [comment]
;)

**Comment by caminantedelossuenos** [comment]
texto cerregido: "Tipos de archivos soportados: .jpg o .png"
