### ISSUE TITLE
¡IMPORTANTE!!! inscripciones

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#100]
Hice una inscripcion a un proyecto, lo cerre, publiqué resultados y exporté la planilla.
Intenté acceder al proyecto desde el link de la planilla y me pidio que me loguera. Creé el usuario jurado. Cuando quiero ver el proyecto logueda me da error.
En el proyecto agregué al jurado sin la posibilidad de editar y me da el mismo error.
Le doy la posibilidad de editar y ahí si puede ver el proyecto.
Esto ya lo he planteado, hace como un año. Esto no puede ser así, porque no puedo darle el poder al jurado de editar el proyecto, osea la convocatoria. Hay programas que tienen hasta sesenta jurados. Que pueden tener intereses personales en inscripciones de otras categorias y al darle el poder de ingresar podrían mirar otras cosas que no les concierne a su categoría.
Se entiende?
Alguien a quien yo le pase la planilla con el link tiene que poder ver el formulario. Para mi se habia arreglado ya esto de alguna forma (no recuerdo efectivamente si fue asi y cual fue la solucion).

![image](https://cloud.githubusercontent.com/assets/17646115/23184804/fc478af0-f85f-11e6-9f53-8df8143009b1.png)

**Comment by mayteloyarte** [comment]
Pendiente y vital

**Comment by leogermani** [comment]
Holas,

Esá hecho. Hice un plugin: https://github.com/LibreCoopUruguay/ProjectCuradores

O plugin já está ativo em http://prueba.culturaenlinea.uy

== Necessito ajuda para testar e ver se está ok!!! ==

-- Como funciona: --

No projeto no qual quer adicionar jurados, crie um grupo de agens chamado "Curadores" (escrito exatamente assim, podemos mudar este nome depois).

Dentro do grupo "Curadores", relacione os jurados.

Qualquer agente dentro deste grupo poderá ver as inscrições, mas não poderá editar o projeto.

* Os curadores poderão ver apenas as inscirções que foram enviadas (não poderão ver as que estão como borrador)

* Os curadores não podem mudar o status das inscrições, apenas ver. 

Por favor testar muito!!!!

@donsalvatore @mayteloyarte

**Comment by mayteloyarte** [comment]
pude crear el formulario cambiar orden etc
pero no puedo isncribirme xq me pide campos q no estan. cree issue con eso.
cuado se saltee eso sigo con el testeo
beso


*Mayte Loyarte*

2017-04-30 20:59 GMT-03:00 leogermani <notifications@github.com>:

**Comment by kterva** [comment]
solucionado en #124

**Comment by leogermani** [comment]
@mayteloyarte você testou o acesso como curador??

**Comment by mayteloyarte** [comment]
no funciona, pasa lo mismo.
y aunque este logueado como jurado cuando hago click en el vinculo de la planilla me vuelve a pedir que me loguee, siendo que ya estoy logueda en ese navegador. me logueo y perdio la ruta.
tengo que ir a modificar hipervinculo, copiar el link y ahi pone bien la ruta pero da acceso denegado
![image](https://cloud.githubusercontent.com/assets/17646115/26020033/87b726a2-3750-11e7-9ad9-4f03e4731e1c.png)

**Comment by leogermani** [comment]
@mayteloyarte creio que você não testou corretamente. Entrei no projeto e não vi nenhum grupo indicando quem são os jurados.

Copio e colo novamente as instruções de como funciona:

-- Como funciona: --

No projeto no qual quer adicionar jurados, crie um grupo de agens chamado "Curadores" (escrito exatamente assim, podemos mudar este nome depois).

Dentro do grupo "Curadores", relacione os jurados.

Qualquer agente dentro deste grupo poderá ver as inscrições, mas não poderá editar o projeto.

* Os curadores poderão ver apenas as inscirções que foram enviadas (não poderão ver as que estão como borrador)
* Os curadores não podem mudar o status das inscrições, apenas ver.

**Comment by mayteloyarte** [comment]
el agente jurado pudo ver la inscripción, pero cuesta llegar a eso.
cuando hago click en el vinculo me pide que me logue (ya estoy logueada), lo hago y pierde la ruta.
Para poder acceder al proyecto tuve que ir a modificar hipervinculo y ahi copiar el link.
Entonces hay que solucionar eso, quizas lo mejor es que en la planilla aparezca el vinculo directamente y no un acceso directo al link. Y de ultima que copien y peguen de la misma planilla, pero no tener que ir a inspeccionar el hipervinculo para encontrar la ruta verdadera.

**Comment by leogermani** [comment]
@mayteloyarte eu não entendo que caminho você está fazendo para ter essa dificuldade. Você pode descrever passo a passo?

 Eu tentei de dois jeitos:


Primeira opção
 1. deslogado, tentei acessar: http://prueba.culturaenlinea.uy/inscripcion/2132611397/
 2. O site me redirecionou para login
 3. fiz login com o usuário "prueba" que você criou
 4. Abriu o formulário


 Segunda opção
 1. LOGADO, visitei a página do projeto
 2. vi a aba "Inscritos"
 3. Vi a lista de inscritos e cliquei no número de inscrição... abriu normal...

**Comment by leogermani** [comment]
Relacionado com https://github.com/hacklabr/mapasculturais/issues/1204

Resolvido
