### ISSUE TITLE
Problemas con la fecha de evento

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#102]
Dice que hay error, no dice cual es.
me pasa cuando pongo fecuencia semanal a todos los dias.
si pongo una sola vez lo carga

![image](https://cloud.githubusercontent.com/assets/17646115/23674475/d4d608f2-0354-11e7-9510-be23ef3f72a8.png)
![image](https://cloud.githubusercontent.com/assets/17646115/23674500/e22634c8-0354-11e7-85b4-ad0e0dfa8a2f.png)

**Comment by leogermani** [comment]
Já contemplada em #106
