### ISSUE TITLE
txt portugues painel

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#107]
![image](https://cloud.githubusercontent.com/assets/17646115/23680423/f269d76c-0369-11e7-8513-eba7824963aa.png)

**Comment by leogermani** [comment]
qual é o texto?

**Comment by kterva** [comment]
es la url, está seleccionado en la barra de dirección de la imagen

**Comment by mayteloyarte** [comment]
Pendiente

**Comment by kterva** [comment]
pronto, de todas formas, chequear
