### ISSUE TITLE
TXT portugues actuacao

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#109]
![image](https://cloud.githubusercontent.com/assets/17646115/23757263/09e79666-04c5-11e7-9226-a9b6125ee8f7.png)

**Comment by mayteloyarte** [comment]
Pendiente

**Comment by kterva** [comment]
solución transitoria
resta aplicar funciones de traducción al archivo src/protected/application/themes/BaseV1/assets/js/directives/find-entity.html
se tradujo en el código
