### ISSUE TITLE
Al crear Espacios aparece el texto "Este espaco esun borrador"

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#11]

**Comment by kterva** [comment]
está en el archivo /mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/entity-status.php la línea 10: <div class="alert warning">Este <?php echo strtolower($entity->entityType)?> es un borrador.</div> 

hay que traducir $entity->entityType y por ahora no sé cómo se hace

**Comment by kterva** [comment]
en la línea 12 del mismo archivo pasa igual

**Comment by kterva** [comment]
para cambiar la palabra "espaço" para que $entity->entityType devuelva la traducción ¿se debe modificar el archivo mapasculturais/src/protected/application/themes/BaseV1/assets/js/mapasculturais.js ?

**Comment by caminantedelossuenos** [comment]
No pasa prueba. sigue saliendo el mensaje "Este espaço es un borrador."

**Comment by caminantedelossuenos** [comment]
confirmado aparece texto ok en español: "Este espacio es un borrador."
