### ISSUE TITLE
error cuando logueo

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#112]
sigue apareciendo esto, refresco y funciona pero cualquier usuario dudo se de cuenta
![image](https://cloud.githubusercontent.com/assets/17646115/23865525/c17995f4-07f4-11e7-952f-b603226024e7.png)

**Comment by leogermani** [comment]
Isto é quando faz login via alguma rede social?

**Comment by mayteloyarte** [comment]
si fb
