### ISSUE TITLE
fecha y tema de ¿importación?

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#114]
Reporte de Error
Cuando se edita la fecha inicial y final de un evento en "Agregar cuándo y dónde", al guardar, quedan las fechas como "Invalid Date"
Luego de varios intentos de repente queda bien. Habría que saber cual es la razón de que se invalide.

Por otro lado, necesitaría contactar con la gente de hizo los ajustes del software a Uruguay, para hablar del tema para que importe los datos de nuestro sitio, sin tener que editar todo dos veces. No se en que situación contractual quedaron, si hay posibilidades de que hagan algo de eso, o si lo hago yo y ellos lo suben, o como sea.

**Comment by kterva** [comment]
amplío explicación:
Por el mail a Maite, todos los eventos quedan "invalid date". Cuando se seleccionan en el calendario quedan bien, pero luego al guardar quedan mal.
Intentamos poner de 14:00 a 19:00 todos los días. Hay algo que se está validando mal.
Lo real sería martes a domingos, pero no importa, pero también da inválido.
Igual se carga el texto "Desde el jueves 2 de marzo al domingo 23      de abril de 2017.", pero el 24 de abril quiero que desaparezca, y si no administra fechas está mal.

**Comment by leogermani** [comment]
Eduardo Ricobaldi enviou a informação que faltava. Era um problema apenas no Firefox.

Está resolvido, entra no ar no próximo release, nos próximos dias.
