### ISSUE TITLE
Wordpress - correcciones

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#115]
http://plandecirculacion.culturaenlinea.uy/
Las fechas estan en portugues
cambiar projeto por proyecto
Que comience en mayúsculas "Publicado por" "Proyecto"

![image](https://cloud.githubusercontent.com/assets/17646115/24565106/2b0924a6-162a-11e7-92f7-eb0c6f21a81b.png)

lo que esta raro es cuanod uno quiere seleccionar el tipo. 
Porque cuando posicionas el cursos en la barra desplazadora los tipos se salen, entonces no puedes correr la barra para elegir otro tipo.
Yo puedo porq mi mouse tiene ruedita pero si no tuviera no podría hacerlo.
![image](https://cloud.githubusercontent.com/assets/17646115/24565159/5b7eb344-162a-11e7-8958-df8c5870601a.png)

**Comment by kterva** [comment]
https://github.com/LibreCoopUruguay/cultural/commit/1c6283843cfce13c81ce07a1dfe4cced3dc3a7ae
