### ISSUE TITLE
Error imprimir certificado

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#116]
![image](https://cloud.githubusercontent.com/assets/17646115/24674113/b92b745e-1950-11e7-9251-5cbb33b349db.png)

**Comment by leogermani** [comment]
Estou trabalhando em várias coisas relacionadas a esta parte. Quando fizer uma atualização revisamos esta issue para ver se resolveu

**Comment by kterva** [comment]
solucionado
