### ISSUE TITLE
ipresión

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#117]
![image](https://cloud.githubusercontent.com/assets/17646115/24807695/9dc9c562-1b8f-11e7-918a-3ef9bb3cdfea.png)

**Comment by leogermani** [comment]
@kterva resolvido?

**Comment by kterva** [comment]
sí en https://github.com/LibreCoopUruguay/mapasculturais/commit/e9cc66df0d7d11f3a33fbadf5d6c44fff511de0d
