### ISSUE TITLE
Logueo con cuenta facebook

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#118]
Primer sitio?
Además no funciona el logueo, la pagina vuelve a la inicial de logueo y no reacciona ante la asociacion con facebook.
![image](https://cloud.githubusercontent.com/assets/17646115/25075252/ac26f00e-22e6-11e7-944a-fa5d2f3a2815.png)

**Comment by leogermani** [comment]
@kterva esto de "primer sitio" no tiene que ver con la configuracion del App de facebook?

**Comment by kterva** [comment]
@leogermani hay que corregir en la url en el config.php "autenticacao" por "autenticacion"
