### ISSUE TITLE
No me deja rechazar notificacion

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#119]
Cuando rechazo la notificación da error porque el proyecto ya no existe, entonces no puedo hacer nada y la notificacion no desaparece.
![image](https://cloud.githubusercontent.com/assets/17646115/25075289/94737efe-22e7-11e7-940b-39adbed5c420.png)

![image](https://cloud.githubusercontent.com/assets/17646115/25075284/87feb12a-22e7-11e7-91f2-4f2d51c812db.png)

**Comment by kterva** [comment]
solucionado
