### ISSUE TITLE
agregar signo exclamación

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#12]
Hola, Mayte Loyarte, bienvenido al panel de Culturaenlinea.uy!
falta el signo de exclamación del comienzo.

Hola, Mayte Loyarte, ¡bienvenido al panel de Culturaenlinea.uy!

**Comment by leogermani** [comment]
Melhorei a string de tradução. Ver https://github.com/LibreCoopUruguay/mapasculturais/commit/5ba8baee65904ce3bb9480633f37f8d72535a15d

@kterva corrige a tradução agora?

**Comment by kterva** [comment]
pronto!! se verá el cambio al hacer la próxima actualización
