### ISSUE TITLE
Bug identificado por Pablo de fondos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#121]
Según me relata el descargó l estructura del formulario y luego la importó en uno nuevo y no le cargó las descripciones de los cambios. y También me dice que
"me cambió la descripción del campo existente (por ejemplo, teatro) y me puso el de videojuegos importando los campos de videojuegos (cosa que sí quería)."

Trato de replicarlo y notifico

**Comment by mayteloyarte** [comment]
intento y replicarlo y no me sale lo mismo

**Comment by kterva** [comment]
se cierra por no poder replicarse el error
