### ISSUE TITLE
admitir url sin https

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#123]
esto ya lo he dicho, en proyectos es. nadie sabe q hay q poner https://
si alguien pone www.dddd.com tiene q ceptarlo. si no se puede quitar el control y q el campo quede abierto
![image](https://cloud.githubusercontent.com/assets/17646115/25874718/314889a4-34ea-11e7-95f9-1fabd6b7da8e.png)

**Comment by kterva** [comment]
Ya hay una issue con esto, por favor no volver a abrir otra
