### ISSUE TITLE
no me deja enviar inscripcion 

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#124]
me pide que complete campos que ya completé
y en rojo pide campos que no estan
![image](https://cloud.githubusercontent.com/assets/17646115/25874817/ba74141e-34ea-11e7-841b-fcf3333fd058.png)

**Comment by kterva** [comment]
falta completar el Género en el perfil del agente que se inscribe;
que aparezca {{raza}} es un error @leogermani

**Comment by kterva** [comment]
solucionado!!! aparecerá en próxima actualización
