### ISSUE TITLE
txt en portugues

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#125]
ya lo he pasado pero no encuentro la issue en q lo ponia
dice ás en vez de a las
![image](https://cloud.githubusercontent.com/assets/17646115/26019827/ee9b3ce8-374e-11e7-9cc0-9713826fd8cf.png)

**Comment by mayteloyarte** [comment]
mas txts en portugues 
![image](https://cloud.githubusercontent.com/assets/17646115/26019872/42c19358-374f-11e7-8d41-6ad60729886b.png)

**Comment by mayteloyarte** [comment]
Área de Atuação
Arquivos

**Comment by kterva** [comment]
a52233d (https://github.com/LibreCoopUruguay/mapasculturais/commit/a52233d1fb3fc6ee1aac4cdeaef9c566b769f7a5): se agregaron funciones de traducción y se actualizó el archivo de idioma español by kterva
