### ISSUE TITLE
TXTs fecha en portugues en prueba.cultura

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#127]
![image](https://cloud.githubusercontent.com/assets/17646115/26465296/0a22cb40-4161-11e7-80f6-a2289870afbd.png)

**Comment by kterva** [comment]
testear en prueba.culturaenlinea.uy y avisar

**Comment by mayteloyarte** [comment]
ahora aparece otro texto 
![image](https://user-images.githubusercontent.com/17646115/37612470-1494658a-2b84-11e8-8390-8aed50e5e2eb.png)

**Comment by kterva** [comment]
¿entonces?

**Comment by mayteloyarte** [comment]
sigue igual
![image](https://user-images.githubusercontent.com/17646115/37612729-c4e52776-2b84-11e8-8a11-238ee093a0f9.png)

**Comment by kterva** [comment]
pronto, verificar

**Comment by mayteloyarte** [comment]
sigue en portugues

**Comment by kterva** [comment]
![imagen](https://user-images.githubusercontent.com/6854552/37693990-1e3cbe92-2ca2-11e8-976c-eca7806a3f2b.png)

**Comment by mayteloyarte** [comment]
los meses siguen en portugués
la captura no se vincula con el issue reportado.

**Comment by kterva** [comment]
pegar link, por favor, porque la url de las imágenes son las mismas

**Comment by mayteloyarte** [comment]
http://test.culturaenlinea.uy/inscripcion/1661166278/

**Comment by kterva** [comment]
listo
