### ISSUE TITLE
Txts en portugués - denuncia contacto

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#129]
![image](https://user-images.githubusercontent.com/17646115/26990773-3845e1a0-4d2e-11e7-994e-be1873699cb0.png)

**Comment by mayteloyarte** [comment]
![image](https://user-images.githubusercontent.com/17646115/26990931-e2fe4362-4d2e-11e7-8606-8522886cd915.png)

**Comment by mayteloyarte** [comment]
cuando pongo denuncia anonima pone ese cartel. xq?

**Comment by kterva** [comment]
verificar si no está solucionado

**Comment by mayteloyarte** [comment]
igual
![image](https://user-images.githubusercontent.com/17646115/37612643-84f328ac-2b84-11e8-93e6-8f0f1d003a3e.png)
