### ISSUE TITLE
En Espacios Debajo del mapa dice DIRECCION: y no da opción de hacer nada.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#13]
Si es un titulo sacarle los dos puntos y cambairle la aparencia para que se diferencie del resto.

**Comment by kterva** [comment]
NO ENTIENDO

**Comment by kterva** [comment]
Está bien que no haga nada, ES UN TÍTULO DEL BLOQUE

**Comment by caminantedelossuenos** [comment]
lo que pide Mayte es que "Si es un titulo sacarle los dos puntos y cambairle la aparencia para que se diferencie del resto."

**Comment by kterva** [comment]
QUEDÓ PRONTO (se sacaron los dos puntos, se puso en mayusculas y en negrita)

**Comment by caminantedelossuenos** [comment]
confirmado ok
