### ISSUE TITLE
Error al enviar emails CONTACTO/DENUNCIA

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#131]
lo de enviar los mails no anda bien, los manda al revés
ej,
Margarita denuncia/contacto a Mayte y le llega un mail a Mayte que dice "Hola Margarita"
Y si Mayte denuncia/contacto a Margarita no le llega nada de que la estan denunciando o queriendo contactarse con ella.

![image](https://user-images.githubusercontent.com/17646115/27194596-830ffa7c-51d9-11e7-941c-e231d0c3c657.png)

**Comment by kterva** [comment]
verificar si sigue pasando

**Comment by mayteloyarte** [comment]
Cuando mandas CONTACTO no hace nada. a nadie le llega mail diciendo que alguien quiere contactarse o lo que sea.
el DENUNCIA pareciera ok

**Comment by kterva** [comment]
solucionado
