### ISSUE TITLE
PROYECTOS: desordena las preguntas en los formularios

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#132]

**Comment by mayteloyarte** [comment]
No puedo replicarlo para descubrir cual es el patron comun.
Pero me ha pasado varias veces que armo un formulario y luego las preguntas aparecen desordenadas.
Me paso ayer con un formulario con 76 preguntas. Ya lo arreglé, pero el año pasado también me pasó con los de museos en la noche.

**Comment by kterva** [comment]
no se pudo replicar

**Comment by mayteloyarte** [comment]
si se puede replicar, issue 140 con capturas
