### ISSUE TITLE
TXTS EN PORTUGUES

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#133]
hay muuuchos textos en portugues todavía.
Projetos aparece muchas veces.

cuando dar enviar en una inscripción al final abajo dice la fecha de envio en portugues.

**Comment by kterva** [comment]
es igual a #131

**Comment by kterva** [comment]
ver campo "Buscar projetos", en el caso de eventos, agentes y espacios no pasa
![capturaprojetos](https://user-images.githubusercontent.com/6854552/37440385-39ec34d6-27db-11e8-8e85-f7462dfb9428.png)

**Comment by kterva** [comment]
ahora no hay muuuuchos, hay meeeenos
