### ISSUE TITLE
FORMULARIO NO ACEPTA 0

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#134]
EN un proyecto de un registro de fotógrafos hay preguntas múltiples (0,1,2,3,4,5,6) q no aceptan 0 como respuesta. Cuando el usuario pone 0 el sistema marca en rojo y dice que la respuesta es obligatoria. Cambié 0 por "ninguna" pero igual, eso está mal. Tendria que aceptar el 0.

**Comment by kterva** [comment]
no se pudo reproducir el error
