### ISSUE TITLE
"mapas culturais"

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#137]
Cuando uno manda el link ej. en whatsapp la imagen q aparece dice mapas culturais.
tiene que ser de cultura en linea

**Comment by kterva** [comment]
se necesita una imagen de 1.200 píxeles de ancho y 630 píxeles de altura, en formato .png

**Comment by mayteloyarte** [comment]
ya les mande por mail la imagen

**Comment by kterva** [comment]
no toma la imagen share.png del tema

**Comment by mayteloyarte** [comment]
?

**Comment by kterva** [comment]
???

**Comment by mayteloyarte** [comment]
leonardo, un signo de pregunta significa interrogante. Ergo no entendi lo que dijiste, si es un comentario para mi o algo tecnico a solucionar entre ustedes.

**Comment by kterva** [comment]
Sí, existen otras vías para hacer una consulta así

**Comment by kterva** [comment]
probar
