### ISSUE TITLE
Visualización proyectos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#138]
No es amigable ni funcional como se muestran los proyectos.
Cambiar criterio abecedario y ponerlo por ID, el mas nuevo primero. Si no parece que la pagina siempre esta igual porque el que empieza con A queda hasta la eternidad figurando primero.

Y sería ideal que se vieran no en lista si no tipo cuadraditos a los costados, como se visualizan los agentes en el wordpress.
Si esto se pudiese aplicar tmb para todas las entidades sería mas vistoso.

**Comment by kterva** [comment]
se mejoraron criterios de búsqueda, agregando más filtros y posibilidad de filtrar sólo por abiertos
