### ISSUE TITLE
en Espacio cambiar formato de telefonos a Uruguay

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#14]
Los formatos de los teléfonos están en brasilero.

**Comment by kterva** [comment]
tenemos 2 tipos de nros, de 8 dígitos (teléfonos fijos) y de 9 dígitos (celulares)
la función quedó así:

$('.js-editable').on('shown', function(e, editable) {
        if ($(this).hasClass('js-mask-phone')) {
            var masks = ['000 000000', '0000 0000'];
            editable.input.$input.mask(masks[1], {onKeyPress:
               function(val, e, field, options) {
                   field.mask(val.length > 9 ? masks[0] : masks[1], options) ;
               }
            });
        }

**Comment by kterva** [comment]
el formato también se controla en los agentes en mapasculturais/src/protected/application/conf/agent-types.php ???? líneas 104 - 112 y 122

**Comment by kterva** [comment]
mapasculturais/src/protected/application/conf/agent-types.php se comentaron las validaciones de los teléfonos

event-types.php idem

spaces-types.php idem

se agrega la siguiente función al archivo editable.js y se comenta su correspondiente de brasil

/*MÁSCARA TELÉFONOS URUGUAY*/
    
    $('.js-editable').on('shown', function(e, editable) {
        if ($(this).hasClass('js-mask-phone')) {
            var masks = ['(000) 00-00-00-00'];
            editable.input.$input.mask(masks[0], {onKeyPress:
               function(val, e, field, options) {
                   field.mask(masks[0], options) ;
               }
            });
        }

PRONTO PARA PROBAR

**Comment by kterva** [comment]
está para probar

**Comment by caminantedelossuenos** [comment]
confirmado ok
