### ISSUE TITLE
Testing enero 17 - Texto en portugués en "Mi cuenta"

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#14]
![image](https://cloud.githubusercontent.com/assets/17646115/21821149/36de5fc0-d751-11e6-8fae-96cc09912743.png)

**Comment by mayteloyarte** [comment]
Separar las palabras "MisProyectos"

**Comment by mayteloyarte** [comment]
"Painel de controle" a "panel de control"

**Comment by leogermani** [comment]
tradução do plugin, com @kterva

**Comment by kterva** [comment]
pronto!!! commit [8969215](https://github.com/LibreCoopUruguay/MultipleLocalAuth/commit/8969215e4324d223d4a5babb916c50c55d202cdf)
