### ISSUE TITLE
URGENTE! Desordena preguntas

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#140]
No solo las desordena cuando lo estas armando (ya lo he reportado varias veces), sino que cuando exportas la planilla tmb.
Ver caso de proyecto Registro fotógrafos.
No mantiene le orden del formulario.

Es urgente ya que hay una convocatoria abierta con 76 preguntas en este momento, y cuando lo exportas aparece primero la 55, luego la 72 y así sigue desordenado.

**Comment by mayteloyarte** [comment]
hICE LAS PREGUNTAS EN EL ORDEN QUE dice su nombre (uno dos tres cuatro cinco) y como ven estan en otro orden. lo q hice fue guardar entre de nuevo y las habia desordenado. tiene q mantener el orden que uno le da cuando lo esta haciendo, no lo que el sistema quiera despues.

![image](https://user-images.githubusercontent.com/17646115/37483650-1ef7a05e-2865-11e8-8ab4-1b6bff9b22b2.png)

**Comment by mayteloyarte** [comment]
las hice con un numero adelante he hizo lo mismo. no mantiene el orden inicial que uno da.

**Comment by leogermani** [comment]
Estamos tratando desta issue aqui: https://github.com/hacklabr/mapasculturais/issues/1341

Raro que nunca logramos reproduzir el problema de se pierder la orden... 

pero sí vemos el problema de la ordenacion de la planilla con las inscripciones

Cuando solucionarmos, aviso aqui. pero depende que hagamos la actualizacion

**Comment by kterva** [comment]
resuelta
