### ISSUE TITLE
suporte@

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#143]
Los mails dicen sUporte

**Comment by kterva** [comment]
listo

**Comment by mayteloyarte** [comment]
ahora no llega ningún mail a ninguno de los implicados.

**Comment by kterva** [comment]
verificar nuevamente, en producción

**Comment by mayteloyarte** [comment]
solo llega ante denuncia y llega OK con soporte

no llega cuando uno pide contacto
sigue mismo error cuando uno quiere mandar anonimo
