### ISSUE TITLE
TXT Portugues en inscripciones

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#144]
cuando uno envía la inscripción
![image](https://user-images.githubusercontent.com/17646115/37618319-acc28eee-2b94-11e8-996a-6f86551f998f.png)

**Comment by kterva** [comment]
hay que chequearlo en prueba, fue comentado en #127

**Comment by kterva** [comment]
pronto, verificar

**Comment by mayteloyarte** [comment]
verificado
