### ISSUE TITLE
en Proyectos aparece texto "liña"

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#15]
Opciones de inscripcion (coloque una opcion por liña)

**Comment by kterva** [comment]
se modificaron mapasculturais/src/protected/application/themes/BaseV1/views/project/create.php y enlaces edit.php y single.php LINEA 315

**Comment by caminantedelossuenos** [comment]
confirmado ok : Opciones de inscripción (coloque una opción por línea)
