### ISSUE TITLE
En proyecto pasar texto a español. En Enviar modelo sale el msg "O arquio enviado nao e um documento valido"

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#16]

**Comment by kterva** [comment]
esto está en mapasculturais/src/protected/application/translations/pt-br.php
¿qué hacemos con ese archivo? ¿lo traducimos o lo cambiamos por uno en español?

**Comment by caminantedelossuenos** [comment]
este mensaje no lo pude reproducir. voy a Proyecto,  Inscripciones. 5. Anexos. y pude subir sin problema los archivos de ejemplo.

**Comment by caminantedelossuenos** [comment]
Listo, confirmado, msg sale en español: "El archivo subido no es un documento válido."
