### ISSUE TITLE
en Proyectos, faltas de ortogradia y portugues en Resultados "Selecionada"

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#18]

**Comment by kterva** [comment]
se tradujeron varios textos en mapasculturais/src/protected/application/themes/BaseV1/assets/js/ng.entity.module.project.js

**Comment by kterva** [comment]
también se tradujo en mapasculturais/src/protected/application/themes/BaseV1/views/project/report.php

**Comment by caminantedelossuenos** [comment]
textos ok: Todas
Pendiente
Inválida
No seleccionada
Suplente
Seleccionada
