### ISSUE TITLE
agregar ciudad y dpto en la vista rapida de los espacios y eventos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#2]
![image](https://cloud.githubusercontent.com/assets/17646115/21204418/1a967e86-c236-11e6-97d4-c968d1281d27.png)

**Comment by leogermani** [comment]
Na lista de espaços ok, na de evento ainda não coloquei, precisamos pensar melhor como fazer, pois um evento pode acontecer em vários espaços, em diferentes departamentos, então não existe apenas 1 departamento para exibir...
