### ISSUE TITLE
En proyectos - en Realizar inscripcion - Termino CP en vez de Documento.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#20]

**Comment by kterva** [comment]
se sacó de la línea 421 el texto ", con un CP válido ingresado" (CP sería código postal ) del archivo /mapasculturais/src/protected/application/themes/BaseV1/views/project/create.php y sus enlaces

**Comment by caminantedelossuenos** [comment]
Al momento de realizar la inscripcion sale el mensaje; "Agente responsable por la inscripción *
Agente individual (persona física) con los campos CI, Fecha de nacimiento/fundación, Género, Email Privado y Teléfono 1 obligatoriamente completados"
