### ISSUE TITLE
En Proyectos - texto en portugues en Agente responsable por la inscripcion.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#22]

**Comment by kterva** [comment]
estos textos aparecen en mapasculturais/src/protected/application/translations/pt-br.php y hay qué ver qué hacemos con este archivo

**Comment by caminantedelossuenos** [comment]
QA verificado ok 
antes decía "Baixar o regulamento"
ahora "Descargar el reglamento"
