### ISSUE TITLE
en Proyectos - quitar el control en raza

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#23]

**Comment by kterva** [comment]
proyectos no tiene control de raza

**Comment by kterva** [comment]
"control" ¿qué significa? no es un campo requerido
¿quieren eliminar el campo?

**Comment by mayteloyarte** [comment]
eliminar que te pida que cargues raza! y sacarlo del texto cuando estas llenando el formulario.

Agente responsable por la inscripción *
Agente individual (persona física) con los campos CI, Raza/Color, Fecha de nacimiento/fundación, Género, Email Privado y Teléfono 1 obligatoriamente completados

**Comment by caminantedelossuenos** [comment]
listo. "Institución responsable (Agente colectivo (persona jurídica) con los campos RUT, Fecha de nacimiento/fundación, Email Privado y Teléfono 1 obligatoriamente completados)"

**Comment by mayteloyarte** [comment]
Para poder inscribirte te pide que llenes obligatoriamente el campo raza. Ese es el control que digo de sacar, osea que no lo exija. Por otro lado no lo puedo verificar porque no está dejando inscribir. Me sigue pidiendo que seleccione una opcion a la hiora de inscribirme y ya la seleccioné.

**Comment by mayteloyarte** [comment]
luego de analizadas las respuestas del issue 41 pude enviar la inscripción y vi que no solicita mas el campo raza. verificado ok
