### ISSUE TITLE
En Proyectos - Inscripcao enviada. Aguarde tela de sumario.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#26]

**Comment by caminantedelossuenos** [comment]
aparece texto en español luego de envio de inscripcion "Inscripción enviada el día 24/03/2016 às 13:50:21 "

**Comment by kterva** [comment]
SOLUCIONADO

**Comment by mayteloyarte** [comment]
ok. Verificado por mi.
no lo muevo de columna xq yo solo muevo las q estan en aprobadas QA no se si está aca por que falta el ok de uds.
