### ISSUE TITLE
en perfil de agente decidir acerca de

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#27]
1 - raza. Mantener o retirar?
2 - sexualidad. Mantener o retirar. Si mantenemos cuales son las tipologias?

**Comment by mayteloyarte** [comment]
Borrar orientación sexual
cambiar raza por Identidad étnica

**Comment by donsalvatore** [comment]
Pero. Identidad etnica son muchas y es in termino muy difícil de poner concepto incluso en la actual antropologia. Es decir: cuales serian las opciones étnicas de uruguay? Seguro que no serian las que ya figuran en la plataforma.

Existe aqui en Uruguay algún departamento del gobierno, oficina o universidad que llevan estas cuestiones? Seria mejor preguntarles. O buscar algun estudio estatístico oficial que llevan el tema.

Ok? 

Miguel Gondim de Castro
+55 11 971612502

**Comment by mayteloyarte** [comment]
borrar ese campo también.
Borrar raza y sexualidad.

**Comment by leogermani** [comment]
removi os campos. Necessário verificar se ainda há algum texto que faz referência a eles

**Comment by leogermani** [comment]
@mayteloyarte confirma que esta issue está resolvida?

**Comment by mayteloyarte** [comment]
Los campos si se sacaron. si aparece en otro lado no se. Que yo sepa solo saltaba cuando uno se iba a inscribir y eso se arregló. si salta en otro lado no lo se.
