### ISSUE TITLE
Sigue pasando que cuando descargo el archivo de inscriptos y hago click en el numero de inscripcion no me abre el formulario si no que me pide el logueo.

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#28]

**Comment by kterva** [comment]
yo lo sigo probando y no me pide logueo, funciona bien. Hay que seguir investigando si sigue pasando

**Comment by mayteloyarte** [comment]
sigue pasando,  esto es vital y define si usaremos o no el mapa para las inscripciones.  como va este asunto? creen que se solucionará? porque deber+iamos pasar cuanto antes a produccion pero esto me preocupa que no se pueda arreglar.
Leo me dijo que el podía, supongo que es por utilizar open office, pero yo pruebo y no funciona, y los jurados usarán probablemente exel como yo.

**Comment by kterva** [comment]
Efectivamente, ocurre con MS Office, con Libre Office u Open Office no ocurre. No es un error.

**Comment by mayteloyarte** [comment]
entonces? se esta buscando una forma de que funcione en todos los tipos de planillas de calculo?

**Comment by leandrodb** [comment]
Como pidió @caminantedelossuenos substituí la columna con el enlace por una con el número y otra con la dirección de la inscripción que puede ser copiada y abierta donde se desee.

**Comment by mayteloyarte** [comment]
Lo del link lo podriamos llegar a solucionar utilizando el drive, hoy se me ocurrio generar el archivo ahi, y en ese caso si te permite ver el proyecto si sos super agente.  En esta compu no tengo ods por lo que no puedo probar nuevamente, pero lo que descubri hoy es que solo puedes ver la lista de inscriptos para acceder al formulario si sos super agente.  Niega el acceso a otros usuarios, aún cuando este agente pertenezca al proyecto y hasta con el permiso de editar activado.
No se si hay otra forma de agregar agentes al proyecto o de permitir a otros agentes que puedan acceder a ver las inscripciones.

**Comment by caminantedelossuenos** [comment]
Mayte,  @leandrodb generó una nueva version de la planilla. sustituyó la columna con el enlace por una con el número y otra con la dirección de la inscripción que puede ser copiada y abierta donde se desee.

**Comment by mayteloyarte** [comment]
verifiqué nueva version y al copiar el link no hay inconveniente.
Sigue pasando que me deniega el acceso a un usuario común... ej. jurado
