### ISSUE TITLE
Eliminar proyectos

### ISSUE THREAD

**Issue by leogermani** [LibreCoopUruguay/mapasculturais#3]
Me deja eliminarlos pero no definitivamente xq tienen inscripciones.
34
21
26
32
27
35
36
30
28
31
29
33

**Comment by leogermani** [comment]
@mayteloyarte Agora na nova versão existe a possibilidade de "arquivar" itens. Você remove ele das buscas mas deixa gravado como arquivo, para que não se perca. O que acha?

**Comment by mayteloyarte** [comment]
ok!

**Comment by kterva** [comment]
verificar si esto está solucionado, creo que sí

**Comment by mayteloyarte** [comment]
si
