### ISSUE TITLE
traducir el datepicker fechas aparecen en portugués

### ISSUE THREAD

**Issue by kterva** [LibreCoopUruguay/mapasculturais#33]

**Comment by kterva** [comment]
fue traducido. Está pronto para probar

**Comment by kterva** [comment]
había quedado Frebei, fue arreglado.

**Comment by kterva** [comment]
SOLUCIONADO

**Comment by mayteloyarte** [comment]
ok. Verificado por mi.
no lo muevo de columna xq yo solo muevo las q estan en aprobadas QA no se si está aca por que falta el ok de uds.
