### ISSUE TITLE
fecha nacimiento agente

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#35]
es complicado seleccionar la fecha de nacimiento, hay q elegir primero el año, porque considera como "enter" de fecha cuando uno selecciona el día, entonces si primero pongo el dia le da ok. luego quiero poner elaño y no hay forma que se guarde el cambio. salvo haga click de nuevo en el numero de dia. yo me di cuenta al rato que era eso, pero no creo que todo el mundo se de cuenta.

**Comment by mayteloyarte** [comment]
el problema es que falta el botón de OK que si aparece en otros campos de fecha por ej. eventos
![image](https://cloud.githubusercontent.com/assets/17646115/22442050/a55d8ab2-e718-11e6-9fc2-75d238b948ee.png)

**Comment by kterva** [comment]
funciona bien. Se seleccionan mes y año y muestra en el calendario el día para seleccionar. Es el comportamiento estándar
