### ISSUE TITLE
mensagem vermelha ao tentar enviar projeto

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#36]
Quando as campos estão incompletos e tentamos enviar o projeto/inscrição o sistema dá a mensagem em português: "Corrija os erros indicados abaixo"

em vermelho no topo da página

**Comment by kterva** [comment]
ese texto no lo encuentro haciendo una búsqueda en el contenido de los archivos del proyecto

**Comment by donsalvatore** [comment]
voy a hacer un print

**Comment by kterva** [comment]
Luego de subir los archivos hay que reiniciar php y nginx
problema solucionado
