### ISSUE TITLE
cambiar la imagen de No verificado, está en portugués

### ISSUE THREAD

**Issue by kterva** [LibreCoopUruguay/mapasculturais#38]
cambiar la imagen de No verificado, está en portugués ¿cómo se debe proceder para cambiarla?

**Comment by kterva** [comment]
se editó la imaguen en portugués.

QUEDÓ PRONTO

**Comment by caminantedelossuenos** [comment]
sigue en portugues para e caso de no verificado

**Comment by caminantedelossuenos** [comment]
confirmado ok imagen en español
