### ISSUE TITLE
En inscreipciones - campos obliugatorios agente

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#41]
para poder inscribir se pide tener lleno raza, ci, telefono etc. eso ya fue arreglado el año pasado de que no se pidiera. :( sera q hay mas cambios perdidos?
Los datos que tiene que tener cargados si o si es CI y email.

esmas cuando estas llenando el formulario dice q hay q tener cargado cedula y luego cuando llenas el formulario te salta conq  hay q cargar raza, y telefono, fecha nacimiento, genero. Eso no se pide.

**Comment by leogermani** [comment]
removi obrigatoriedade. Necessário verificar se ainda há algum texto que faz referência a eles

**Comment by mayteloyarte** [comment]
igual está el control. el usuario tiene cargado ci y email q fue lo q pedi obligatorio y salta el control de cosas q faltan y estan en portugues.

p.d: leo t use tu usuario xq con el mio no puedo y no queria usar un usuario de alguno ajeno.

![image](https://cloud.githubusercontent.com/assets/17646115/22441954/3cf89674-e718-11e6-88ed-b3d7fa710a80.png)

**Comment by leogermani** [comment]
Fiz um teste e consegui fazer a inscrição. Apesar de o texto (em portugues) dizer que outros campos são obrigatorios, eles não são.

Já descobri porque o texto está em português e vou trabalhar para resolver isso.

Por favor façam mais um teste e confirmem isso por favor.

Os campos obrigatórios são apenas: Documento e email privado.
