### ISSUE TITLE
Error en la inscripción a un proyecto: se activa la validación del campo categoría, aunque se elija una de las opciones (aparece caja roja: Este agente necesita tener el campo "Categoría" completo)

### ISSUE THREAD

**Issue by kterva** [LibreCoopUruguay/mapasculturais#41]

**Comment by leandrodb** [comment]
Las configuraciones de inscripciones (registrations) en proyectos están [aquí](https://github.com/LibreCoopUruguay/mapasculturais/blob/master/src/protected/application/conf/conf-base.php#L94)

**Comment by kterva** [comment]
no lo encontré ahí.
Cuando en un proyecto que están habilitadas las inscripciones y se está realizando la inscripción. Si se agregó una categoría a las incripciones, se selecciona una de las opciones y al dar enviar la inscripción, aparece la validación del campo

**Comment by leandrodb** [comment]
Si. Caso el proyecto posea categorías, entonces, debe ser una información requerida. No tiene sentido? Aquí está la validación: https://github.com/LibreCoopUruguay/mapasculturais/blob/master/src/protected/application/lib/MapasCulturais/Entities/Registration.php#L378

**Comment by kterva** [comment]
da el error cuando se selecciona cualquier opción

**Comment by leandrodb** [comment]
Puede pegar aquí el contenido de la requisición de la aba red del web
inspector?
Para vermos qué está siendo enviado y qué está siendo retornado.
Seguro que está enviando una categoría?
Cuales son las categorías y cual está enviando?
abs

**Comment by kterva** [comment]
a ver si es esto?

GET /inscricao/404839/ HTTP/1.1
Host: mapa-test.cultura.mec.gub.uy:98
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:44.0) Gecko/20100101 Firefox/44.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://mapa-test.cultura.mec.gub.uy:98/projeto/4/
Cookie: __utma=171207679.360737172.1434508519.1434508519.1434508519.1; _ga=GA1.3.360737172.1434508519; __utma=137359394.360737172.1434508519.1441328076.1441335948.2; PHPSESSID=5flagioujt39e7c0f8imgdiqc3; mapasculturais.uid=7
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 09 Mar 2016 03:32:39 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.13
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: mapasculturais.uid=7; path=/
mapasculturais.adm=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Content-Encoding: gzip

**Comment by kterva** [comment]
El mensaje que aparece es porque se quiere enviar una inscripción sin antes salvar. Lo que se debe hacer es Salvar antes de enviar la inscripción.
Tenemos que agregar texto al mensaje que aparece en rojo, avisando que el campo ha cambiado y se debe salvar antes de enviar

**Comment by kterva** [comment]
se agregó texto aclaratorio de que hay que salvar antes de enviar la inscripción. Está para probar

**Comment by mayteloyarte** [comment]
Sucede que el texto de que es necesario salvar antes de enviar solo aparece cuando uno guarda, por ende la persona solo lo verá si ya guardó. No se podrá poner ese texto en otro lado? Por otro lado, sacarle los tres signos de exclamación! queda muy violento.

**Comment by kterva** [comment]
QUEDÓ PRONTO lo pedido por @mayteloyarte
