### ISSUE TITLE
Traducción portugues

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#44]
cuando se despliega el calendario en eventos el mismo está en portugues.

**Comment by mayteloyarte** [comment]
solo pasa con el mes de febrero, dice Febrei

**Comment by kterva** [comment]
ya está solucionado

**Comment by mayteloyarte** [comment]
ok. Verificado por mi.
no lo muevo de columna xq yo solo muevo las q estan en aprobadas QA no se si está aca por que falta el ok de uds.
