### ISSUE TITLE
Sacar control https://

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#45]
En los campos de agregar link no los acepta si no tienen el formato con https://. Pero eso lo se yo, porque el control solo dice que es inválida la url. No acepta www solo. Por favor sacar el control y que quede libre.

**Comment by kterva** [comment]
LISTO
se comentaron en el código <<entidad>>-type.php las validaciones de las url

**Comment by mayteloyarte** [comment]
ok. Verificado por mi.
no lo muevo de columna xq yo solo muevo las q estan en aprobadas QA no se si está aca por que falta el ok de uds.
