### ISSUE TITLE
Usuario de Mayte no permite autenticacion con cuenta de facebook

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#5]

**Comment by leandrodb** [comment]
Esto pasa en la producción, correcto? En el ambiente de test, pasa?

**Comment by caminantedelossuenos** [comment]
en el ambiente de test no le permite a ella autenticarse con su usuario de fb

**Comment by caminantedelossuenos** [comment]
mi usuario si permite autenticacion en fb en el mismo ambiente de test

**Comment by kterva** [comment]
el usuario de facebook no tenía correo electrónico asociado.

ESTO QUEDÓ PRONTO

**Comment by caminantedelossuenos** [comment]
confirmado ok
