### ISSUE TITLE
Exportar datos con dpto

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#50]
Las exportaciones por ej. de espacios no dicen el departamento. Este dato es fundamental para filtrar datos. Por favor agregar ese campo.

**Comment by kterva** [comment]
"filtrar datos" ¿dónde?

**Comment by mayteloyarte** [comment]
Necesitamos que las exportaciones ya sea de agentes de espacios o eventos tengan una columna donde diga el departamento.

**Comment by mayteloyarte** [comment]
esto es fundamental! si no la exportacion carece de sentido. es el dato diría mas importante.

**Comment by mayteloyarte** [comment]
ok. no me deja mover los issues para la otra columna pero esta verificado.
