### ISSUE TITLE
ZIP planilla inscriptos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#51]
La planilla de inscriptos no exporta el paquete de archivos adjuntos en un zip. tenia entendido que eso si pasaba. La columna archivos queda en blanco.

**Comment by kterva** [comment]
fue probado en dos instalaciones separadas y por dos personas distintas y la planilla de inscriptos SÍ trae el archivo zip con el contenido de los archivos adjuntos. Se debe probar con una inscripción con adjuntos, porque sino el sistema no genera el archivo zip. Si no hay archivos adjuntos, la columna archivo estará vacía

**Comment by mayteloyarte** [comment]
yo lo pruebo y no trae los zip, y sí tiene archivos adjuntos. es en testing proyecto Inscripción.

**Comment by donsalvatore** [comment]
Si!
Igual a pasado con mis pruebas y que tb llevava un archivo adjunto

Miguel de Castro Perez 
+55 11 971612502

**Comment by mayteloyarte** [comment]
acabo de hacer un proyecto se llama 123456 y no exporta los archivos zipeados... lo hago en testing. sera un problema se mi usuario? no lo se pero a mi  no me funciona

**Comment by donsalvatore** [comment]
si! igual paso con mi prueba!
incluso sigue alli las pruebas. en producción y test

2016-04-29 14:00 GMT-03:00 mayteloyarte <notifications@github.com>:

> acabo de hacer un proyecto se llama 123456 y no exporta los archivos
> zipeados... lo hago en testing. sera un problema se mi usuario? no lo se
> pero a mi no me funciona
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LibreCoopUruguay/mapasculturais/issues/51#issuecomment-215810736>
>



-- 
Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502

**Comment by kterva** [comment]
solucionado, el s.o. del server no tenía ZIP instalado
