### ISSUE TITLE
No acceso a formulario

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#52]
Sigue sin permitir a un usuario externo acceder a inscripciones. Tomo el archivo y me logueo, pero cuando quiero ver el formulario me niega el acceso. Salvo sea super agente

**Comment by donsalvatore** [comment]
Hola a todos!!

Para empezar tanto en teste como en produccíon
al guardar el proyecto (pestaña inscripciones) me da error desconocido, hay
que recargar la pagina para pode publicar el proyecto.


*en test*
http://mapa-test.cultura.mec.gub.uy:98/

he bajado esta planilla de prueba (adjunta)
estoy en una maquina con openoffice


A estando fuera del sistema (sin autenticarse)

1 - en la celda "numero" el numero no ha salido como enlace como lo debería
creo yo. Igual la celda URL no sale como enlace, hay que copiar y pegar
2 - la celda archivo .zip no me ha venido

B estando autenticado del sistema (sin autenticarse)

1 - la celda URL me lleva a eso a permission denied pero como yo he crado
el proyecto deberia tener esta permisíon


*ahora en producción*

he bajado esta planilla de prueba (adjunta)
estoy en una maquina con openoffice


A estando fuera del sistema (sin autenticarse)

1 - en la celda "numero" el numero no ha salido como enlace como lo debería
creo yo. Igual la celda URL no sale como enlace, hay que copiar y pegar
2 - la celda archivo .zip no me ha venido

B estando autenticado del sistema (sin autenticarse)

1 - la celda URL ha funcionado
2 - igual no me sale el .zip


2016-04-22 1:01 GMT-03:00 leonardo <notifications@github.com>:

> Assigned #52
> <https://github.com/LibreCoopUruguay/mapasculturais/issues/52> to
> @donsalvatore <https://github.com/donsalvatore>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/LibreCoopUruguay/mapasculturais/issues/52#event-637140036>
>



-- 
Miguel de Castro Perez
http://about.me/migueldecastro
@serra_lheria
cel.: +55 11 97161 2502

**Comment by caminantedelossuenos** [comment]
Estimados, buenos días, en base a las pruebas que hizo Miguel entiendo 
entonces que no se tiene acceso por parte de los jurados a los 
formularios a ser evaluados?

Como hacemos para corregir esto? Que recomiendan?

**Comment by kterva** [comment]
No es necesario estar logueado para que se pueda descargar el archivo .zip. Una persona que no está registrada en el sistema, con la url (que va en la planilla en el link ZIP) puede descargarse el archivo zip. Para ver los datos de la inscripción (sensibles), sí hay que estar logueado

**Comment by mayteloyarte** [comment]
pero no deja ver el formulario! niega el acceso, mucho menos va a dejar ver archivos.

**Comment by kterva** [comment]
los campos del formulario están todos en la planilla de datos exportados. Acordamos que alcanza con darle un formato mejor a la planilla
