### ISSUE TITLE
EVENTOS : necesidad de que el campo inscripciones acepte enlaces

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#52]
isso por conta da divulgacao de formularios de inscricao

**Comment by leogermani** [comment]
Você quer dizer que os links se tornem automaticamente clicáveis?

**Comment by donsalvatore** [comment]
sim!!!
pq lá vc divulga o formulário de inscrição

**Comment by kterva** [comment]
resuelto
