### ISSUE TITLE
Cambio icono en navegador

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#55]
esta el MC hay q cambiarlo. 
![image](https://cloud.githubusercontent.com/assets/17646115/22516629/1f342dc4-e885-11e6-9463-2159c80b21e1.png)

Se que comunicacion debe el logo, pero dejo este issue para tenerlo presente.

**Comment by kterva** [comment]
Es un favicon

**Comment by kterva** [comment]
¿está pronto el favicon?

**Comment by leogermani** [comment]
listo
