### ISSUE TITLE
Error al exportar datos agentes

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#56]
la planilla que exporta levanta los datos corridos y me parece q datos no publicos ej. telefono
![image](https://cloud.githubusercontent.com/assets/17646115/22516963/4d578b96-e886-11e6-9ca1-1e6745f2155a.png)

**Comment by donsalvatore** [comment]
As tabelas estão com os dados trocados.
Não testei as outras as são dois problemas

1 - saíram os dados públicos mesmo eu não estando logado
2 - oa dados não correspondem as colunas

**Comment by leogermani** [comment]
vejo que os campos estão errados, os valores não correspondem as colunas.

Mas os campos privados não estão saindo se quem faz download não está logado.

Vou corrigir
