### ISSUE TITLE
nombre

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#57]
al espacio 911 no me deja ponerle de nombre casa de la cultura. Entre a cambiarle el tipo de museo a oficina cultural y tuve q ponerle un punto para que lo guardara. No dice cual es el error, se me ocurre que no pueden haber mas de un espacio con el mismo nombre, es asi?

**Comment by kterva** [comment]
Efectivamente, no pueden haber espacios con el mismo nombre. Aunque se puede cambiar esta validación
