### ISSUE TITLE
Carregar shapefiles de departamentos (y otros?)

### ISSUE THREAD

**Issue by leogermani** [LibreCoopUruguay/mapasculturais#6]
como fazer:

https://github.com/LibreCoopUruguay/mapasculturais/blob/master/documentation/docs/mc_deploy_shapefiles.md

**Comment by leogermani** [comment]
Consegui converter os shapefiles para o formato correto. Tive ajuda de um amigo e estou tentando documentar como fazer isso.

O arquivo sql gerado é este:

[deptos_shp.sql.zip](https://github.com/LibreCoopUruguay/mapasculturais/files/709076/deptos_shp.sql.zip)

Com este arquivo, basta seguir os últimos passos da documentação, que consistem em carregar esta tabela no banco de dados e inerir os registros na tabela geo_location

**Comment by kterva** [comment]
¿en qué estado quedó esto?

**Comment by leogermani** [comment]
Já está
