### ISSUE TITLE
En el formulario de Agente el campo telefono esta en formato brasilero y no en formato Uruguay

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#6]
Se solicitar cambiar a formato Uruguay  o al menos a formato Internacional

**Comment by kterva** [comment]
ver comentario issue #14

**Comment by kterva** [comment]
QUEDÓ PRONTO PARA PROBAR

**Comment by mayteloyarte** [comment]
quien prueba? ya es en testing?

**Comment by mayteloyarte** [comment]
sacarle el control y dejarlo abierto, sin control. q la gente solo pueda poner numeros y +, pero sin control de cantidad

**Comment by caminantedelossuenos** [comment]
telefono permite poner hasta 11 numerosTeléfono 1: 111 11 11 11 11
