### ISSUE TITLE
tamaño de archivos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#60]
no deja subir archivos que pesan mas de 1 mb! intento subir las bases de un fondo abierto y no me deja, probé otros archivos y queda cargando. llega al 100% y no hace nada.
esto es vital!

**Comment by kterva** [comment]
chequear configuración de php y/o nginx

**Comment by kterva** [comment]
para ampliar la capacidad de memoria de subida de archivos
Agregar en /etc/nginx/nginx.conf

client_max_body_size 20M;

Y EN  /etc/nginx/sites-avialable/mapas.conf

server {
listen *:80;
server_name www.meu.dominio.gov.br;
return 301 $scheme://meu.dominio.gov.br$request_uri;
client_max_body_size 20M;   <<<<<<<<----------------
}

**Comment by mayteloyarte** [comment]
por favor solucionar esto!!!

**Comment by mayteloyarte** [comment]
la semana q viene son las inscripciones y el mapa no deja subir archivos livianos. poner limite tipo 5 mb.
