### ISSUE TITLE
Inscripciones abiertas problema

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#61]
http://culturaenlinea.uy/projeto/99/

ya se termino el periodo de inscripciones hacen 6horas.
Si voy a Proyectos in hago clic en "inscripciones abiertas (el fitro) me aparece la el proyecto

**Comment by donsalvatore** [comment]
mas o filtro deve buscar apenas inscrições abertas (efetivamente).
segue do mesmo jeito

**Comment by leogermani** [comment]
me dá o exemplo que você testou e não funcionou.

**Comment by donsalvatore** [comment]
pode fechar ;)
