### ISSUE TITLE
Error en agenda de proyecto

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#63]
![image](https://cloud.githubusercontent.com/assets/17646115/22561775/7e8648ec-e958-11e6-8022-1b07f9512df7.png)

**Comment by leogermani** [comment]
https://github.com/hacklabr/mapasculturais/issues/1101

**Comment by leogermani** [comment]
Nâo conseguimos mais reproduzir este erro
