### ISSUE TITLE
Quiero inscribir y no deja

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#64]
Selecciono el agente con el q quiero inscribir, le doy "realizar inscripcion" y no hace nada. 
Sí, tengo los datos obligatorios cargados.
![image](https://cloud.githubusercontent.com/assets/17646115/22561820/bc9a5b6e-e958-11e6-95db-d1074d993eeb.png)

**Comment by donsalvatore** [comment]
Leo isso, acho eu, que são os agentes antigos do sistema. Hj aconteceu isso de novo com uam pessoa que fez a primeira aula da capacitação

**Comment by mayteloyarte** [comment]
en otro proyecto sí me dejó inscribirme, con el mismo usuario. Capaz sea algo con ese proyecto.

**Comment by leogermani** [comment]
provavelmente problema igual a #80
