### ISSUE TITLE
En formulario

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#67]
1.- Cuando uno está llenando los campos como titulo dice
"Campos adicionales. 
Para afectuar su inscripción, complete los campos abajo."
Sacar todo eso y no poder nada, puede ser?

2.- y cuando uno lo manda donde dice "Campos adicionales del formulario de inscripción." que no diga nada. Simplemente que liste los campos del formulario completos.

3.- Por otro lado. Me marea lo de los sellos... donde dice "Sellos certificadores que serán atribuidos a los agentes de la inscripción cuando la misma fuera aprobada." poner "Sellos certificadores que serán atribuidos a los agentes de la inscripción en caso que su propuesta sea seleccionada."

4.- Se puede poner eso de los sellos al final? no en el medio del formulario? porque no se entiende mucho y la gente se va a marear con eso. Como se que no se puede sacar si es posible que aparezca al final del formulario y no en el medio.

**Comment by kterva** [comment]
1 y 2 ¿sacar?
3 - solucionado

**Comment by mayteloyarte** [comment]
si! 1 y 2 sacar

**Comment by kterva** [comment]
@leogermani

**Comment by leogermani** [comment]
estou consultando as pessoas aqui no Brasil para ver se fazemos isso para todo mundo, ou apenas para culturaenlinea

**Comment by leogermani** [comment]
Removido título "Campos adicionales" y toda la seccion "Sellos"
