### ISSUE TITLE
Planillas de exportación - traducción pges-esp

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#69]
Traducir campos de las columnas a español

**Comment by mayteloyarte** [comment]
levanta el campo edad pero vacío, no se si habia una formula que calculaba la edad o un campo fantasma donde cada uno ponia su edad. No es relevante. Borrar

**Comment by mayteloyarte** [comment]
levanta dos veces localizacion y dirección

**Comment by leogermani** [comment]
- [x] remover campo idade
- [x] traduzir campos que estão em portugues
- [x] remover localização e direção duplicada
- [x] remover campo "departamento" duplicado (geoDepartamento)

**Comment by leogermani** [comment]
Sobre os campos duplicados:

## Direccion y Direccion

é um tema da tradução. 

O primeiro campo "Direccion" é o endereço completo, que junta todas as informações de rua, numero, bairro, etc...

O segundo campo "Direccion" é chamado, originalmente, de "nome do logradouro", ou seja, o nome da rua ou da avenida...

**Comment by kterva** [comment]
Verificar si esto está solucionado

**Comment by mayteloyarte** [comment]
No.
Todos (agentes,espacios,eventos,proyectos) tienen campos en pgues. Otros campos se llaman registrationFrom registrationTo

**Comment by mayteloyarte** [comment]
no entiendo lo de dirección. que levante la direccion cargada.

**Comment by leogermani** [comment]
@kterva que opinas sobre a tradução de "Direccion" que eu descrevi alguns comentários acima?

**Comment by kterva** [comment]
@leogermani  creo que habría que eliminar "O segundo campo "Direccion" é chamado, originalmente, de "nome do logradouro", ou seja, o nome da rua ou da avenida..."
