### ISSUE TITLE
Planilla exporta inscriptos no levanta adjuntos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#70]
![image](https://cloud.githubusercontent.com/assets/17646115/22566597/7221b2cc-e96b-11e6-9260-b85c374f70a2.png)

**Comment by donsalvatore** [comment]
es verdad

**Comment by leogermani** [comment]
https://github.com/hacklabr/mapasculturais/issues/1100

**Comment by leogermani** [comment]
Faltava instalar o ZIP no servidor.

Está resolvido para as inscrições enviadas a partir de agora.
