### ISSUE TITLE
Traduccion pgues-esp

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#71]
en proyectos inscriptos
![image](https://cloud.githubusercontent.com/assets/17646115/22567323/40eb8e8c-e96e-11e6-865b-f298a520552a.png)

**Comment by mayteloyarte** [comment]
![image](https://cloud.githubusercontent.com/assets/17646115/22567689/bc0e2d76-e96f-11e6-877b-8b580db8250d.png)

**Comment by mayteloyarte** [comment]
todas as opcoes
inscirpcion enviada "ás"=a las
responsável

![image](https://cloud.githubusercontent.com/assets/17646115/22567765/04b2aade-e970-11e6-80e9-8ef19dd4cbb9.png)

**Comment by kterva** [comment]
están en archivos .js /mapasculturais/src/protected/application/themes/BaseV1/assets/js/ng.entity.module.project.js

Responsável fue solucionado en mapasculturais/src/protected/application/themes/BaseV1/layouts/parts/singles/project-registrations--tables--published.php

**Comment by kterva** [comment]
verificar si está solucionado

**Comment by mayteloyarte** [comment]
verificado
