### ISSUE TITLE
Cambio de txt en inscripciones

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#72]
Sacar "de"
que quede: "Numero de inscripción"
y que sea mas chico. Es demasiado grande. que tenga un tamaño normal.

![image](https://cloud.githubusercontent.com/assets/17646115/22568286/0248ef36-e972-11e6-8c2e-4bdb02b78ce3.png)

**Comment by donsalvatore** [comment]
eso no estoy de acuerdo y este numero es si importante. Lo de achicar significa disminuir las possibilidade de protocolos

**Comment by mayteloyarte** [comment]
no digo de borrarlo, digo de sacar la palabra "la". en español no decimos numero de la inscripcion, osea se dice pero queda raro.
Que quede "número de inscripción" no "número de la inscripción"
y que el numero de inscripción sea mas chico. Me parece groseramente grande y a nosotros DNC no nos sirve de mucho.
Reitero, no estoy diciendo de borrar. Estoy pidiendo que se edite el texto y el numero tenga algun punto menos de tamaño.

**Comment by kterva** [comment]
se sacó el "la"

**Comment by leogermani** [comment]
listo

![captura de tela de 2017-02-06 12-16-53](https://cloud.githubusercontent.com/assets/971483/22650474/87a193c6-ec66-11e6-8354-e51aff9e9fbb.png)
