### ISSUE TITLE
urgente::::necessidade de todas as dimensões de imagens do site

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#76]
parea podermos fazer os logos e selos etc precisamos ter as dimensões das imagens de toda a plataforma.

Já existe isso?

**Comment by leogermani** [comment]
LOGO até 72px de altura / +- 200px de largura

marca da organização (topo direito, opcional) - até 72px de altura / até 90px de largura

avatar padrão - 144px 144px

favicon - icone de 14px - ver: http://stackoverflow.com/questions/2268204/favicon-dimensions

Imagem de fundo da home: indefinido. Pode ser bem grande, para se ajustar a diferentes monitores.

Ex:

http://spcultura.prefeitura.sp.gov.br/
http://mapa.cultura.df.gov.br/ (olhar no exemplo apenas o tamanho da imagem, e não o efeito de trocar várias imagens que foi desenvolvido especificamente para aquele site)

**Comment by donsalvatore** [comment]
E a imagem do header?

Miguel Gondim de Castro
+55 11 971612502

**Comment by leogermani** [comment]
Que imagem do header?

**Comment by donsalvatore** [comment]
Todos os perfis das entidades tem um header. Aquela imagem retantular logo acima da foro de perfil de qualquer entidade.

Miguel Gondim de Castro
+55 11 971612502

**Comment by leogermani** [comment]
Essa imagem varia a largura de a acordo com a resolução da tela da pessoa.

Então pode ser uma imagem de 1200x192 , mas percebendo que em algumas telas a área visível dela pode ser apenas os 600px centrais. E no celular também come um pouco a altura.
