### ISSUE TITLE
Implementar consulta de endereço por código postal no tema culturaenlina

### ISSUE THREAD

**Issue by leogermani** [LibreCoopUruguay/mapasculturais#8]
Instruções:

https://github.com/LibreCoopUruguay/mapasculturais/blob/master/documentation/docs/mc_developer_geocoding.md

**Comment by leogermani** [comment]
@kterva Pode colocar aqui o link para a API dos correios do Uruguai?

**Comment by kterva** [comment]
**áreas administrativas diva-gis** http://biogeo.ucdavis.edu/data/diva/adm/URY_adm.zip
**mapas vectoriales ine 2011** http://ine.gub.uy/documents/10181/18006/Mapas+Vectoriales+a%C3%B1o+2011/97dbcd58-80a8-472c-86cc-e8ecdaafef99

**búsqueda de direcciones** - webservice correo uruguayo http://www.correo.com.uy/index.asp?pagVal=527

**Comment by leogermani** [comment]
A API dos correios não possui uma consulta por Codigo Postal que retorne o endereço.

O objetivo desta issue era facilitar o preenchimento do endereço, como acontece no mapa do Brasil. QUando a pessoa preenche o codigo postal, os campos de rua, bairro, cidade e estado são preenchidos automaticamente. No caso a API dos correios do Uruguai não oferece esta funcionalidade. Além disso, no Uruguai cada CEP se refere a uma localidade, então não ajudaria muito de qualquer maneira.

Por isso encerramos esta issue.
