### ISSUE TITLE
en Eventos Traducción para LIBRAS​, que es?

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#8]

**Comment by kterva** [comment]
LIBRAS = língua brasileira de sinais (Libras) é a língua de sinais (língua gestual) https://pt.wikipedia.org/wiki/L%C3%ADngua_brasileira_de_sinais

**Comment by mayteloyarte** [comment]
Poner "Traducción en lengua de señas"

**Comment by kterva** [comment]
LISTO

**Comment by mayteloyarte** [comment]
ok. Verificado por mi.
no lo muevo de columna xq yo solo muevo las q estan en aprobadas QA no se si está aca por que falta el ok de uds.
