### ISSUE TITLE
agente Silvia Listur http://culturaenlinea.uy/agente/352/ no logra inscribirse

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#80]
no projetop http://culturaenlinea.uy/projetos/edita/115/#tab=sobre
eram 5 minutos antes de fechar

**Comment by leogermani** [comment]
Isso acontece as vezes. Já identifiquei o problema:

https://github.com/hacklabr/mapasculturais/issues/1103

**Comment by donsalvatore** [comment]
Massa.
Sabe explicar pra mundanos?

Miguel Gondim de Castro
+55 11 971612502

**Comment by leogermani** [comment]
Não tem muito como explicar de maneira não técnica.. era um bug mesmo. Uma situação que não estava prevista que gerava um erro... mas não tinha a ver com nada nenhuma situação em particular...
