### ISSUE TITLE
Barra lateral derecha en Agente: Agentes

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#88]
SOY MAYTE
Se puede sacar el campo de agentes de al lado? no el de admiistrador.
sino la incorporacion de los agentes.
xq esta desordenado y no agrupado, entonces marea. Hay varios agentes que pertenecen a un grupo ejemplo fondos, o ciudadania y territorio. No queremos crear mas agentes que agrupen cosas xq se hace infinito el arbol.
Puede ser como era antes? yo creo el grupo de agentes y meto dentro los que yo quiera?
http://culturaenlinea.uy/agente/19/
planteo esto a demanda de comunicacion, coincido con ellos.

**Comment by leogermani** [comment]
Creio que seja melhor então deixar apenas para o dono do agente. Por que é bom ter um lugar onde se possa ver todos os filhos do agente, certo?

**Comment by donsalvatore** [comment]
Acho que nunca podemos esquecer que o mapas é um bando de dados. marearse com informação de fato pode atrapalhar mas o sistema tem que deixar cada vez mais clara as relações para que a gestão da infomação seja fácil... o lugar de consulta e divulgação e no mareo seria no site wordpress.

que acha?

**Comment by mayteloyarte** [comment]
PENDIENTE
Sacar el listado de agentes hijos de la barra lateral derecha.
Quizas ponerlo en otro lado ej. al lado de agenda o en otro lado. Pero ahí marea.
Esto es a pedido de comunicación.

**Comment by donsalvatore** [comment]
pero es una información importante. 
Cambiar de sitio porque marea? Jeje

Miguel Gondim de Castro
+55 11 971612502

**Comment by mayteloyarte** [comment]
Esto es algo que no estaba, apareció hace poco. Preferimos la versión anterior que no lo tenía, por lo menos no en la barra lateral derecha.
Por eso consulto si no se puede meter en otro lado tipo al lado de la agenda.

**Comment by leogermani** [comment]
Mayte, não é possível fazer isso neste momento.

É um custo muito alto para personalizar isso e ficar diferente da versão oficial em um momento que estamos passando por várias atualizações... Podemos fazer isso mais para o futuro, ok?
