### ISSUE TITLE
pesteñas agenda en espacios, proyectos y agentes

### ISSUE THREAD

**Issue by donsalvatore** [LibreCoopUruguay/mapasculturais#89]
acontece com o perfil 371 que publica pelo museo nacional de artes.
em todas as abas das entidades o evento http://culturaenlinea.uy/evento/77/ nao aparece para ela.

se dou log off ou estou com outra agenda rola!!

**Comment by leogermani** [comment]
https://github.com/hacklabr/mapasculturais/issues/1101
