### ISSUE TITLE
Se solicita cambiar textos que aparecen en portugues

### ISSUE THREAD

**Issue by caminantedelossuenos** [LibreCoopUruguay/mapasculturais#9]
por ejemplo en Descripción legible del horario aparece en portugues

**Comment by caminantedelossuenos** [comment]
Cuando se ingresa una fecha sigue apareciendo la descripcion en portugues. Vuelvo este issue a la columna Entrada

**Comment by kterva** [comment]
QUEDÓ PRONTO

**Comment by caminantedelossuenos** [comment]
descripcion legible dia y mes aparecen en español
