### ISSUE TITLE
Selecionado em edital não consegue atribuir evento ao projeto

### ISSUE THREAD

**Issue by leogermani** [LibreCoopUruguay/mapasculturais#90]
O projeto ao qual foi selecionado não aparece como possibilidade na hora de cadastrar eventos

**Comment by leogermani** [comment]
https://github.com/hacklabr/mapasculturais/issues/1099

**Comment by mayteloyarte** [comment]
Solucionado parcialmente, problema con el link de autorizacion en notificaciones.

**Comment by leogermani** [comment]
solucionado
