### ISSUE TITLE
Agregar tipo de evento: Visita

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#91]
Agregar tipo de evento
Visita

**Comment by mayteloyarte** [comment]
veo que ahora está el tipo visita guiada, yo le sacaría el guiada porque pueden haber visitas libres.
en todo caso que en el detalle se aclara que es guiada o en el nombre del evento.

Entonces poner tipo Visita

**Comment by mayteloyarte** [comment]
Pendiente

**Comment by leogermani** [comment]
Listo, entra no ar no próximo release
