### ISSUE TITLE
Solicitud campos formulario

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#93]
Es posible agregar "campos" dentro del formulario que su tipo sea título.
Es decir que el usuario que se inscribe no tenga que llenar nada. Porque hay preguntas que son grupales, o se necesita un texto aclarando las características de las preguntas (se que se puede hacer uno por uno, pero cuando son muchas la cosa cambia).
ej. titulo: Datos personales
y bajo ese titulo esten las preguntas.

Surge a demanda del sistema de info cultural que tienen formularios y se les presentó ese problema.

**Comment by mayteloyarte** [comment]
pendiente

**Comment by leogermani** [comment]
Sim, esta é uma boa idéia que outras pessoas já demandaram também. Vou trabalhar nisso. Agora que os campos são ordenáveis isso faz mais sentido!
