### ISSUE TITLE
Sacar txt en subir bases

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#95]
En formatos aceptados dejar solo pdf
que quede así "Envíe un archivo con las bases. Formato aceptado: .pdf."

no es necesario cambiar el control, dejarlo como está. Pero que la gente crea que solo tiene que subir pdf. si no igual te suben un documento oficial en word con logos y todo y es peligroso.

![imagen](https://cloud.githubusercontent.com/assets/17646115/23174693/f039df2a-f83b-11e6-995a-db1bafad6b02.png)

**Comment by mayteloyarte** [comment]
pendiente

**Comment by leogermani** [comment]
@kterva puedes hacer esto en la traduccion?

**Comment by kterva** [comment]
listo en https://github.com/LibreCoopUruguay/mapasculturais/commit/6a128d30f7867939c3c0f5c3fa00d759c41c210a
