### ISSUE TITLE
Notificación resultados inscripciones en proyectos

### ISSUE THREAD

**Issue by mayteloyarte** [LibreCoopUruguay/mapasculturais#99]
El usuario que inscribe un proyecto deberia recibir una notificación cuando se publican los resultados y su proyecto fue asigando con alguna categooria ej. seleccionado, no seleccionado, etc.
Lo propongo, no se si esta contemplado o ya se hace en otro lado.

**Comment by mayteloyarte** [comment]
Pendiente

**Comment by leogermani** [comment]
Ok, vou trabalhar nisso
